### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by RaptaG** [enjarai/recursive-resources#1]
:)

**Comment by enjarai** [comment]
This is planned for the first release. After I get the code into a state I'm happy with, it'll be very easy to port to 1.19.2 as well.

**Comment by RaptaG** [comment]
I also plan to make a README for this project!

**Comment by enjarai** [comment]
I think the current README sums it up well enough, but if you think you can do better, feel free to PR. :)

**Comment by RaptaG** [comment]
Can I have the CF and Modrinth mod IDs (if available)?

**Comment by enjarai** [comment]
I haven't made the pages yet, I'm working on that right now. I can send them over once I have a page draft set up, but you wont be able to see them until I start uploading files.

**Comment by RaptaG** [comment]
> I haven't made the pages yet, I'm working on that right now. I can send them over once I have a page draft set up, but you wont be able to see them until I start uploading files.

It's ok, I want them for the README

**Comment by enjarai** [comment]
I've created the pages, I'll put the first release up in a moment.

Modrinth: https://modrinth.com/mod/recursiveresources with id `CcL3MXyI`
Curseforge: https://www.curseforge.com/minecraft/mc-mods/recursive-resources with id `674907`

**Comment by enjarai** [comment]
1.19 version published.
