### ISSUE TITLE
Add default folder icon change with textures

### ISSUE THREAD

**Issue by e-splat** [enjarai/recursive-resources#10]
i noticed that recursive resource doesn't change the default folder icon if a texture pack has one in it, when support for it?

**Comment by e-splat** [comment]
![immagine](https://user-images.githubusercontent.com/82027617/205130902-3e91cbc5-f6ad-467a-bac9-ba24da91af9a.png)

**Comment by enjarai** [comment]
This seems to be due to me using a legacy way of loading the textures, which I inherited from Resource Pack Organiser. It'll be fixed in the next update.
