### ISSUE TITLE
Add support for VTDownloader

### ISSUE THREAD

**Issue by Imzxhir** [enjarai/recursive-resources#14]
Description: Basically the title. Currently if you use both mods together, it looks very weird as seen from the screenshots.

Screenshots: 
![image](https://user-images.githubusercontent.com/98621617/216780967-9fae4e2b-6aec-4bfd-a67e-7fe0f4f859b1.png)

**Comment by enjarai** [comment]
Huh, thats definitely not ideal. I'll look into it.

**Comment by enjarai** [comment]
Seems like this is the same problem as https://github.com/ByMartrixx/VTDownloader/issues/17.

**Comment by enjarai** [comment]
Closing this as its been fixed on VTDL's side.
