### ISSUE TITLE
Resource packs with the same name are displayed only in one place

### ISSUE THREAD

**Issue by Felix14-v2** [enjarai/recursive-resources#16]
I will try to catch this bug and find a conflicting mod, but it doesn't look like there is any way to reproduce it, this bug always appears randomly (I hate "floating" bugs)

https://user-images.githubusercontent.com/75726196/228940734-56f8106f-8188-4146-a301-12129390a738.mp4

[latest.log](https://github.com/enjarai/recursive-resources/files/11115069/latest.log)

UPD: Minecraft no longer sees this resource pack 0_0
[Переводы всего.zip](https://github.com/enjarai/recursive-resources/files/11115398/default.zip)

**Comment by enjarai** [comment]
Can you try to send a log that captures the moment a pack dissapears? It might not, but if it contains a clear error I'll at least have something to go on.

**Comment by Felix14-v2** [comment]
> captures the moment a pack dissapears?

The log above was recorded at this moment, I even caused a diagnostic crash so as not to lose it. And yeah, I can confirm, that this pack now disappears with your mod and vorks fine without it.

**Comment by enjarai** [comment]
Ah my bad, didn't notice the attached log. There seem to be a lot of errors about an `invalid CEN header`, but nothing that'd explain this odd behaviour.

The strangest part is that my mod changes nothing about pack loading itself, it just tells MC to do more of it, so I'm not sure what could be going wrong. I'll see if I can replicate it on my machine when I have time.

**Comment by Felix14-v2** [comment]
Thanks! In the worst case scenario, I will send you my entire Minecraft instance.

**Comment by Felix14-v2** [comment]
By the way, could you make the text in your mod translatable? I would like to suggest translations into my language, but at the moment I just can't do that.

**Comment by enjarai** [comment]
Oh I see, good catch! This *shouldn't* be too hard to fix, I'll definitely look into it. 

Translations are a good idea, I suppose not having those is a leftover from Resource Pack Organizer. I'll let you know once I've pushed those so you can work on a PR if you want.

**Comment by enjarai** [comment]
Lang file support added in [c366e8e](https://github.com/enjarai/recursive-resources/commit/c366e8ecd7bb22158a201b4d6c6dbe2d775d41af), I'll work on the bugfix in a bit.
