### ISSUE TITLE
Can't launch latest version of Recursive Resources for 1.19.3

### ISSUE THREAD

**Issue by variety754** [enjarai/recursive-resources#19]
I updated mod to 2.4.0 through CurseForge app, but on launch I got this
![image](https://user-images.githubusercontent.com/124847943/236574777-31850919-394a-4e1f-ac02-65fb5ac45448.png)

**Comment by enjarai** [comment]
Seems like that file was incorrectly marked compatible with 1.19.3. I've updated the settings on curseforge, so this shouldn't happen again, but you might have to manually select the correct file for it to work again.
