### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by JustCauseWhyNot** [enjarai/recursive-resources#20]
I don't really know why though. Here's [crash log](https://gist.github.com/JustCauseWhyNot/7bb169420d9e46651c4242b099aa0d51) it should tell you whats wrong hopefully. I'd really like to use this mods as it seems super dope. And I love your mods :wink:

**Comment by SplendidAlakey** [comment]
Happens only with 2.4.0, for now downgrading to 2.3.0 works.

**Comment by JustCauseWhyNot** [comment]
While 2.3.0 Isn't crashing. The mods still not working completely correctly, or i'm daft. Here's [log](https://gist.github.com/JustCauseWhyNot/47c7b10b7f66fbf8e401e933a8776487).

**Comment by enjarai** [comment]
Found the issue. Not sure what triggered it, but it was an edge case I hadn't accounted for. A fix should be out soon in 2.4.1.

**Comment by JustCauseWhyNot** [comment]
Thank you very much!

**Comment by enjarai** [comment]
No problem! 2.4.1 is currently publishing.

**Comment by JustCauseWhyNot** [comment]
Quick question. Do I have to create the folder outside of mc for it to show up, or am I supposed to be able to do that in game?

**Comment by enjarai** [comment]
There's currently no way to manage folders and packs ingame, so you'll have to do it in a file browser. This has to do with my eternal nemesis: Windows file locking. 

Apparently, when Minecraft loads a pack to display it on the pack screen, Windows decides it would be a great idea to lock that file to prevent it from being moved. This means that full file browser-like functionality regretfully just isn't possible from what I can tell.

**Comment by JustCauseWhyNot** [comment]
Not a problem! Well 2.3.0 would've probabaly worked then, but I wasn't able to figure out how to make a folder. But now that I know what to there shouldn't be any issues. 

Thank you for your help, and for making & maintaining awesome mods!

**Comment by SplendidAlakey** [comment]
Hey, just a heads-up, the latest upload for 1.19.2 got incorrectly tagged as 1.19-1.19.4 compatible, instead of 1.19-1.19.2. On both Modrinth and CurseForge.

**Comment by enjarai** [comment]
Ah, forgot about it doing that. Thanks for letting me know.

**Comment by Cape-City** [comment]
![grafik](https://user-images.githubusercontent.com/122229367/236882344-9d95e831-250b-4737-86e0-d88ee6a06845.png)

The latest version is also wrong tagged and did not load within a 1.19.3 profile

**Comment by enjarai** [comment]
> ![grafik](https://user-images.githubusercontent.com/122229367/236882344-9d95e831-250b-4737-86e0-d88ee6a06845.png)
> 
> The latest version is also wrong tagged and did not load within a 1.19.3 profile

This was already fixed a while ago, try readding the mod.

**Comment by Cape-City** [comment]
Ok, it seams that only the CurseForge client has a problem with this two versions - the last one indeed isn't shown up there
![grafik](https://user-images.githubusercontent.com/122229367/236898613-2b63104b-a0e1-4a8b-92f1-e9aa12fc4d95.png)

On their website, if i filter to 1.19.3, only the correct available version is shown up:
![grafik](https://user-images.githubusercontent.com/122229367/236898851-6da207e9-a82a-4991-b8f2-ffef0fee3341.png)

Just wondered...sorry for the mention
