### ISSUE TITLE
A "Cancel"-button would be nice

### ISSUE THREAD

**Issue by Cape-City** [enjarai/recursive-resources#22]
In the MC standard, you can move things from left to right or vice versa, one item at a time, and when you press the ESC key, the changes are activated, just as if you had clicked "Done".
In your mod, if you accidentally hit the "Activate All" button instead of just opening the folder and want to undo that, a "Cancel" button would be very helpful or just hitting the ESC key and nothing has changed at all.

**Comment by enjarai** [comment]
This seems like a good idea, I'll look into it.

**Comment by enjarai** [comment]
Added in 2.5.2. Its slightly jankily implemented due to how vanilla works, so let me know if there are any issues.
