### ISSUE TITLE
Resourcepacks provided by other mods (like Continuity) don't show up

### ISSUE THREAD

**Issue by RomanPro100** [enjarai/recursive-resources#23]
Continuity has two built-in resourcepacks, but if I play with both of the mods, these resourcepacks don't show up in the left menu.

Same thing happens if I first play just with Continuity, enable these resourcepacks, then launch with Recursive Resources too and disable them. They do appear in the right menu, but not in the left after I disable them. The video below shows exactly this behavior.

https://user-images.githubusercontent.com/99795209/236669156-d4b2fd22-0512-48ea-a824-35f7405d2177.mp4

**EDIT:** this was in version 2.4.1 of the mod, I also tested with 2.3.0 and everything works fine there, these resource packs do appear.

**Comment by enjarai** [comment]
Apparently I missed something in determining the location of a resource pack, it should be fixed in 2.4.2.
