### ISSUE TITLE
[Feature Request] Wiki/Faq

### ISSUE THREAD

**Issue by JustCauseWhyNot** [enjarai/recursive-resources#24]
I think there should be some more documentation on how to use this mod. Because I myself have some questions that aren't answered. For instance how to create folders isn't easily figured out if you didn't know like I did until I asked you in [this issue](https://github.com/enjarai/recursive-resources/issues/20#issuecomment-1537089411). And other questions like moving resource packs in and out of certain folders, and which folders have priority. Or another thing like what the arrows at the top of the screen do. Unless you play around with this mod those questions aren't easily answered.

This is a great mod I just wish there was a usage guide of sort, or something along those lines.

**Comment by enjarai** [comment]
Thats definitely a good idea, though I'll have to think about how to approach it. It'll probably come down to a big revamp of the README + mod page description, which definitely isn't something I enjoy doing. 😅 

I'll see what I can do.

**Comment by enjarai** [comment]
I've taken the time to rewrite most of the README, very similar changes will be made to the mod page descriptions. Definitely go check it out and let me know if its understandable: https://github.com/enjarai/recursive-resources#readme

**Comment by JustCauseWhyNot** [comment]
Insane change! I find it much more clear, and now have a much better understanding on how to use this nod. Thank you so much!

**Comment by JustCauseWhyNot** [comment]
I noticed did notice one thing while giving looking through more thoroughly right now. It's about the [folder section](https://github.com/enjarai/recursive-resources#folders).

> this mod **cannot create or manage folders ingame** 

Does this mean that you can't move resource packs in between the folders in game, or is it meaning the mod can't create or delete folders in game?

**Comment by JustCauseWhyNot** [comment]
And last thing I can think of at the moment. If you move resource packs into a folder while the game is running can you reload/update the folder or resource pack while in game?

**Comment by enjarai** [comment]
> I noticed did notice one thing while giving a more thorough read right now. It's about the [folder section](https://github.com/enjarai/recursive-resources#folders).
> 
> > this mod **cannot create or manage folders ingame**
> 
> Does this mean that you can't move resource packs in between the folders in game, or is it meaning the mod can't create or delete folders in game?

Good question, I'll update the wording there.

> Also I can't find which issue it was, but it stated how folder priority worked & how it was alphabetical based. I didn't see that mentioned in the readme. Maybe I missed it, but if I didn't that's something that the readme should include. That being how resource pack priority is handled with the folders.

Thats not included because its outdated information as of 2.4.x. Pack apply priority is discussed [here](https://github.com/enjarai/recursive-resources#folderjson-configuration)

> And last thing I can think of at the moment. If you move resource packs into a folder while the game is running can you reload/update the folder or resource pack while in game?

Anything you change in the file browser should update in realtime, I'll mention that in the README as well.

**Comment by enjarai** [comment]
> Ok I'm spamming (sorry I'm just now going through and trying to use this mod) this thread, but I'm confused. Is the folder view supposed to show all the packs that are turned on in the selected screen? Because I thought folder view was also supposed to apply to the selected screen as well. Since it seems it doesn't I'm going to open a mini issue in this thread. Does my new understanding mean that the name of the resourcepack folders not matter in determining the priority of individual resourcepacks, and that it's handled like vanilla?
> 
> [Feature Request] Have an option to have selected screen mimic available screen.
> 
> How I imagined this mod working is that in the specific folder is where you sort out the order of the resourcepacks in that folder and what's on and off. And then in the global view you'd just see the folders in the selected screen. ![2023-05-10_10-29](https://user-images.githubusercontent.com/58643844/237456656-c3338e8a-f601-4b0d-96b7-7b91abfac40e.png)

Folders do intentionally not have any effect on the selected part of the screen. It'd make it very easy to accidentally leave a pack enabled, causing confusing situations. It'd also make the eventual order packs are applied in completely unclear.

**Comment by enjarai** [comment]
Considering this fixed, as mod pages are updated.
