### ISSUE TITLE
Disabling ItemSwapper pack Disappears it.

### ISSUE THREAD

**Issue by JustCauseWhyNot** [enjarai/recursive-resources#26]
I found this out, and thought it was an [issue](https://github.com/tr7zw/ItemSwapper/issues/150#issue-1712422886) with itemswapper. But it turns out if I disable this mod the issue disappears.

**Comment by enjarai** [comment]
This is a known issue with Quilt currently (see #25). For now, the only workaround is to use Fabric instead.

**Comment by JustCauseWhyNot** [comment]
I see. Thanks for the timely response.
