### ISSUE TITLE
Is there a way to solve the errors?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [enjarai/recursive-resources#27]
Basically I think it's being caused by your mod, since when I remove it doesn't happen. If not my bad but if so is there a way to solve this? It may be related to one of the open issue but not sure

https://mclo.gs/bfoKlhO

**Comment by enjarai** [comment]
I don't see any critical errors in this log that would cause a crash, but some incompatibilities with Quilt are a known issue. (See #25) I suggest using Fabric with my mods, as I don't have the time to actively support two modloaders.

**Comment by Aces-and-Jacks** [comment]
Ok. Also your probably not interested in doing it but wouldn't architectury allow you to support fabric and quilt? I'm not a coder so I don't know how hard that'd be

**Comment by jacg311** [comment]
Architectury sadly wouldnt help here. This mod uses fabric internal things that you usually wouldnt use as a mod dev or even look at. 
Quilt has systems that achieve the same goal as fabric but are quite different in the implementation.
Architectury only helps you with things that you would commonly use on both mod loaders.

So for recursive-resources you'd have to write the same thing twice. once for fabric, once for quilt

**Comment by Aces-and-Jacks** [comment]
oh, well that's a shame. Thanks for responding though
