### ISSUE TITLE
Ability to hide the "enable/disable all" buttons

### ISSUE THREAD

**Issue by Felix14-v2** [enjarai/recursive-resources#28]
Mainly compatibility request – there are some mods that also adds their own buttons to the resource pack screen, and when they overlap, it becomes impossible to use them without problems. For example, when using [Resourcify](https://github.com/DeDiamondPro/Resourcify), it is impossible to open the internal browser without disabling all active resource packs:
![image](https://github.com/enjarai/recursive-resources/assets/75726196/47c1d3bb-7d00-4aa1-887c-296af2e45342)

As for my personal user experience, I've never used these two buttons and would gladly disable them for UI minimalism.

Another solution would be to change the approach to performing these actions. Instead of buttons, the action will be applied by clicking on the corresponding section title: when hovering over it, the text will be replaced with something like `Enable all` or `Disable all`:
![image](https://github.com/enjarai/recursive-resources/assets/75726196/317a9024-5cbd-4d44-b025-32c4710aeb4a)

**Comment by enjarai** [comment]
I actually really like the alternative solution you suggest, having a simple mockup to understand what you mean is very helpful. I'll work on implementing it soon.

**Comment by enjarai** [comment]
Added in 2.5.0.
