### ISSUE TITLE
Clicking Below Resourcepacks Enables/Disables All

### ISSUE THREAD

**Issue by Thanos1716** [enjarai/recursive-resources#30]
When clicking on the empty space below the resourcepack list on either side, or the scrollbar (as well as the header), all resourcepacks are enabled/disabled in the current folder. I believe anywhere apart from the headers should be considered a bug, because I keep accidentally clicking it

Below is a screenshot of the affected areas, green indicates the area that applies all packs, red indicates the area which removes.
![2023-07-04_22 05 12-1](https://github.com/enjarai/recursive-resources/assets/80975570/73a2c612-fee9-449e-a737-6f6e0a961455)

Love RR btw, was looking for something like it forever

RR version: 2.5.1+1.20 (Curseforge)
Minecraft version: 1.20.1
Java version: openjdk 17.0.7 2023-04-18
Launcher: PrismLauncher

**Comment by enjarai** [comment]
Nice catch, I'll fix it in the next update.

**Comment by enjarai** [comment]
Fixed in 2.5.2.

**Comment by EnderMelody** [comment]
could you reduce the box on the right side a bit more? the scroll bar is currently covered by the enable/disable all still and i keep clicking it when trying to scroll.
