### ISSUE TITLE
[Bug] folder config file is reset whenever resource pack menu is opened

### ISSUE THREAD

**Issue by ConradwithaK** [enjarai/recursive-resources#37]
For someone like me who uses like 10+ resource packs at once, it is extremely important to deploy them in the correct order, but after I put mine into a folder in the correct order, they deployed alphabetically in-game. Please add a way to control the deploy order.

**Comment by enjarai** [comment]
This is a feature that already exists, though its a little unintuitive to use. See the `folder.json configuration` section of the mod's project page.

**Comment by ConradwithaK** [comment]
I have just re-ordered them in there for the third time, but when I check in-game and then come back to the file, they're back to being alphabetical. I am 100% saving my changes.

**Comment by ConradwithaK** [comment]
Every time I reopen the game, it erases any changes I've made to the folder config file including the deploy order I've set and the folder description.

**Comment by enjarai** [comment]
Make sure you close the resource pack screen while making edits, then reopen it after. I should probably add a check for that honestly...

**Comment by ConradwithaK** [comment]
That is in fact the issue, but when I reopen the resource pack screen it still undoes my edits.

**Comment by enjarai** [comment]
Hmm thats definitely not supposed to happen, maybe a recent update broke something there. I'll look into it.

**Comment by enjarai** [comment]
I'm unable to recreate this issue on the latest 1.20.4 version, what version of the mod are you using?

**Comment by ConradwithaK** [comment]
I was using the latest version from modrinth as of last evening. Can’t elaborate further until I get home.

**Comment by enjarai** [comment]
Hmm okay thats quite strange then. Just to eliminate factors, what OS are you using? (It shouldnt matter, but it might??)

**Comment by ConradwithaK** [comment]
Windows 11 Pro I think (not entirely sure cuz I’m on a new laptop)

**Comment by enjarai** [comment]
Okay that probably isnt it then, I'll try some stuff. 

I'm also thinking the mod might be replacing the json file because its not correctly formatted. If it is, thats not intended behaviour, but it *would* explain your issue. Maybe try running your file through a json linter before opening the pack screen again when you get home?

**Comment by ConradwithaK** [comment]
I’ll try it, but I think it was the right format because all I did was ctrl+x each pack listing and ctrl+v into the right order.

**Comment by ConradwithaK** [comment]
That was the issue. When had I copied the lines for the texture pack listings, I was also copying the commas at the end of each line, so in the middle of the list there was no comma and at the end there was one. Took me a second to figure it out after opening the json linter, but it worked. Thanks for the help!

**Comment by enjarai** [comment]
Ah okay, good to know its fixed. I'll see if I can add some more clear validation for this kind of stuff instead of just overwriting the file.
